name: MCP Codegen → PR

on:
  workflow_dispatch:
    inputs:
      jiraKey:
        description: 'Jira ticket key (e.g., ABC-123)'
        required: true
      title:
        description: 'Short change title'
        required: true
      description:
        description: 'What to generate/change'
        required: false

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Generate changes from ticket
        env:
          TICKET_KEY: ${{ inputs.jiraKey }}
          TICKET_TITLE: ${{ inputs.title }}
          TICKET_DESC: ${{ inputs.description }}
        run: |
          node ./scripts/codegen/generate.js

      - name: Create branch, commit, and push
        env:
          TICKET_KEY: ${{ inputs.jiraKey }}
        run: |
          slug=$(echo "$TICKET_KEY" | tr '[:upper:]' '[:upper:]')
          branch="feature/${TICKET_KEY}-mcp"
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git checkout -b "$branch"
          git add -A
          git commit -m "${TICKET_KEY}: scaffold changes via MCP codegen"
          git push --set-upstream origin "$branch"

      - name: Open Pull Request
        uses: actions/github-script@v7
        with:
          script: |
            const jiraKey = core.getInput('jiraKey');
            const title = core.getInput('title');
            const body = core.getInput('description') || '';
            const branch = `feature/${jiraKey}-mcp`;
            const defaultBranch = context.payload.repository.default_branch;
            const pr = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `[${jiraKey}] ${title}`,
              head: branch,
              base: defaultBranch,
              body: body + "\n\nGenerated by MCP codegen."
            });
            core.setOutput('pr_number', pr.data.number);


